# roles/mariadb/tasks/root-password.yml
---

# This command will fail when the root password was set previously
- name: Check if root password is set
  shell: >
    mysqladmin -u root status
  changed_when: false
  failed_when: false
  register: root_pwd_check
  tags: mariadb

- name: Set MariaDB root password for localhost, 127.0.0.1, ::1
  mysql_user:
    name: root
    password: "{{ mariadb_root_password }}"
    host: "{{ item }}"
    login_user: root
    #login_password: "{{ mariadb_root_password }}" # if nessesary
    login_unix_socket: "{{ mariadb_socket }}"
    check_implicit_admin: yes
    state: present
  with_items:
    - localhost
    - ::1
    - 127.0.0.1
  when: root_pwd_check.rc == 0
  tags: mariadb

- name: Copy ~/.my.cnf for root
  template:
    src: root_my.cnf.j2
    dest: /root/.my.cnf
    owner: root
    group: root
    mode: 0600
  when: root_pwd_check.rc == 0
  tags: mariadb
